apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-swhs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/vigneshsri-tenant/devfile-sample-go-basic-1/devfile-sample-go-basic-swhs@sha256:d815b49f326b7f34727630aba99428ae1a8214a988e8f920dfb7e7d5a4af0611
        name: my-go
        resources: {}
status: {}
